### PR TITLE
Remove LOG: prefix from log message in test

### PR DESCRIPTION
**Pull request by fckt**
Tests are executing against `nearcore` `staging` branch and we are failing with. But in the same time, we can't merge https://github.com/nearprotocol/nearcore/pull/1715 into `staging` cause CI fails to run test of nearlib (it uses master). How to resolve this ?

### CODE REVIEW

**Comment by vgrichina** [comment]
> Tests are executing against `nearcore` `staging` branch and we are failing with. But in the same time, we can't merge [nearprotocol/nearcore#1715](https://github.com/nearprotocol/nearcore/pull/1715) into `staging` cause CI fails to run test of nearlib (it uses master). How to resolve this ?

Need to guard given tests by `nearcore` version

**Comment by nearmax** [comment]
> > Tests are executing against `nearcore` `staging` branch and we are failing with. But in the same time, we can't merge [nearprotocol/nearcore#1715](https://github.com/nearprotocol/nearcore/pull/1715) into `staging` cause CI fails to run test of nearlib (it uses master). How to resolve this ?
> 
> Need to guard given tests by `nearcore` version

How do you do that?

**Comment by vgrichina** [comment]
> > Need to guard given tests by `nearcore` version
> 
> How do you do that?

Query version from server using `/status` endpoint, compare to expected version using https://www.npmjs.com/package/semver, and then execute different tests based on result.

**Comment by vgrichina** [comment]
@fckt in addition to guarding test also needs to revert whitespace changes. Formatting should match `.eslintrc` rules.

**Comment by fckt** [comment]
Done.
But the problem is that we don't know in witch version the original PR going to be enabled. A solution could be just use a regex, not a strict compare. What do think @vgrichina?

**Comment by vgrichina** [comment]
> But the problem is that we don't know from witch version this will going to be enabled. 

Let's merge this when we know which version then? Not sure how regex would help.

**Comment by fckt** [comment]
> Not sure how regex would help.

I mean just check for a substring instead of the strict compression. 

> Let's merge this when we know which version then?

ok

**Comment by nearmax** [comment]
@vgrichina Could you please review it?

**Comment by vgrichina** [comment]
@nearmax @fckt  merged it for now, we can just update the version later if breaks CI

**Comment by bowenwang1996** [comment]
looks like the PR in nearcore is not merged https://github.com/nearprotocol/nearcore/pull/1715, which blocks the PR https://github.com/nearprotocol/nearcore/pull/1871 that updates testnet

**Comment by nearmax** [comment]
Correct, @janedegtiareva decided when to merge.

**Pull request merged**
